trigger:
- main

pool: default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    mavenOptions: '-Dmaven.repo.local=$(Systewm.DefaultWorkingDirectory)'
- task: CmdLine@2
  inputs:
    script: |
      buildah bud --tls-verify=0 --format=docker -t alerantdevopsbootcamp.azurecr.io/bootcamp/demoapp_studentN -f Dockerfile .
      buildah login --tls-verify=0 -u alerantdevopsbootcamp -p VQq7EvmIbRzlT9N6Z/HA4xND8=dQYyYg alerantdevopsbootcamp.azurecr.io
      buildah push alerantdevopsbootcamp.azurecr.io/bootcamp/student4